### PR TITLE
Disable privateMsgButton in trade channel

### PR DESCRIPTION
**Pull request by DrColver**
An exception is thrown when trying to open a private chat in the trade channel. Private chat is only allowed after taking a trade offer.

### CODE REVIEW

**Comment by HenrikJannsen** [comment]
Hm... I think we should permit in trade channel private messages also in case no offer is taken. A taker might have questions to the maker and might prefer to do that as private message. I would need to look into the code what causes the exception and what could be required to support non-trade PMs. Maybe it complicate things too much if we allow that...

**Comment by HenrikJannsen** [comment]
@DrColver 
I had quite some larger pending work which I just put into a PR (https://github.com/bisq-network/bisq2/pull/694) to not get too far away from main branch. Did not had much time recently to work on it... If you have any changes in the notifications area maybe better to base the PR on my branch if it takes longer until merged.

Are you in the matrix channels as well?

**Comment by DrColver** [comment]
The exception is thrown on purpose when someone tries to private message in the trade channel, so it looks like it is not intended to be allowed.

If it should be allowed, maybe it would be better to have a different button on the offer message to just ask a question and not show intention to trade. Then the offer owner knows what the message is in reference to.

Not on matrix. How to join?

**Comment by DrColver** [comment]
With the changes in https://github.com/bisq-network/bisq2/pull/700 it would be possible to include the related offer when opening a new private channel. The offer could be used as a reference when sending a private message without taking the offer.

This PR should not be merged and usage of the correct private message handlers should be used.

**Comment by HenrikJannsen** [comment]
> With the changes in #700 it would be possible to include the related offer when opening a new private channel. The offer could be used as a reference when sending a private message without taking the offer.
> 

Yes, that would be good. The UX is not fully worked out atm in that area. Feel free to suggest what makes most sense to you.

> This PR should not be merged and usage of the correct private message handlers should be used.

You can convert it to a draft (somewhere at the top right in GH).

**Comment by DrColver** [comment]
Fixed in #805

**Pull request closed without merging**
