### PR TITLE
Update translations for v2.0.5

### PR DESCRIPTION
**Pull request by hiciefte**
I updated all translations for the v2.0.5 release

### CODE REVIEW

**Review by djing-chan — APPROVED** [review]
utACK

**Comment by djing-chan** [comment]
Build fails at `SepaAccountTest`:
`assertThat(result.getCreationDate()).isCloseTo(currentTimeMillis(), offset(1000L));`

I assume thats just caused by a delayed thread in the build > 1 seconds. I guess we should remove that test line or at least make it larger then 1 sec.

**Comment by djing-chan** [comment]
@hiciefte Your commits are not signed. Can you fix that?

**Comment by hiciefte** [comment]
@djing-chan Sorry - I completely missed your messages. I updated, rebased, merged and squashed the commits. I hope it should be fine now 🤞

**Review by djing-chan — APPROVED** [review]
utACK

**Pull request merged**
