### PR TITLE
Add info popup when max number of favourites has been reached

### PR DESCRIPTION
**Pull request by axpoems**
Give user feedback when max num. of favourites has been reached.

image

### CODE REVIEW

**Review by HenrikJannsen — CHANGES_REQUESTED** [review]
I think the FavouriteMarketsService should not be handled as a static class. I understand the reasons to have convenient access, but it decreases architecture to use global/static classes for such use case. It is ok for utils but service classes should follow the existing pattern to be created by higher level services and passed to the clients (we pass service classes in item renderer classes to make them available there).

**Comment by axpoems** [comment]
> I think the FavouriteMarketsService should not be handled as a static class. I understand the reasons to have convenient access, but it decreases architecture to use global/static classes for such use case. It is ok for utils but service classes should follow the existing pattern to be created by higher level services and passed to the clients (we pass service classes in item renderer classes to make them available there).

I followed the pattern used in [DontShowAgainService](https://github.com/bisq-network/bisq2/blob/main/settings/src/main/java/bisq/settings/DontShowAgainService.java), which is the other service built on top of settings. Should that one be changed as well then?

**Comment by HenrikJannsen** [comment]
> > I think the FavouriteMarketsService should not be handled as a static class. I understand the reasons to have convenient access, but it decreases architecture to use global/static classes for such use case. It is ok for utils but service classes should follow the existing pattern to be created by higher level services and passed to the clients (we pass service classes in item renderer classes to make them available there).
> 
> I followed the pattern used in [DontShowAgainService](https://github.com/bisq-network/bisq2/blob/main/settings/src/main/java/bisq/settings/DontShowAgainService.java), which is the other service built on top of settings. Should that one be changed as well then?

Yes that should be changed as well IMO.

**Comment by axpoems** [comment]
@HenrikJannsen - Updated the PR with the refactor of `FavouriteMarketsService`.

**Pull request merged**
