### PR TITLE
Add supported languages icon in offer message

### PR DESCRIPTION
**Pull request by axpoems**
Based on #2240 

* Add supported languages icon.
* Replace string with icon and only show languages on hover.

image

### CODE REVIEW

**Comment by djing-chan** [comment]
The icon for supported languages is not very clear to me. 
What about adding the country flags for the given language. I know that is not always a clear association but commonly used (for english it could be half UK. half US). It would give the users also a quick filter for the languages they are interested in without need to rollover the icon. If the icon is rather small I think it will not take too much visual attention but still give a bit of color dot to the otherwise grey design.

**Comment by axpoems** [comment]
About the supported languages, I want to call out a few things:
1. Supported languages is not an action button and should therefore, imo, not be in the react toolbar.
2. We need to clear out that space now to fit in the reactions, since that long string with supported languages takes too much space.

So, for (1) I think we have to tackle the UX problem itself, we have an issue for it #1918, we can work on this later. And for (2) I think having this icon with the tooltip is a good transition step. This icon is the standard used for languages in many applications.

And to brush on the supported languages topic, imo, if I am a user trading in a particular market, I would expect all the users there to be proficient with the language(s) in that country. So I think there's no need to indicate supported languages. But, as I said, I think we can postpone this discussion.

Also, I'm not in favour and would avoid to use country flags (or mixed flags) to represent languages. You seem to know this already, so I won't delve into it.

**Comment by HenrikJannsen** [comment]
>  ...if I am a user trading in a particular market, I would expect all the users there to be proficient with the language(s) in that country. 

In EUR market there are many diff. languages and English is not that much use in Latin language countries.

**Review by HenrikJannsen — APPROVED** [review]
utACK

**Pull request merged**
