### PR TITLE
Update dropdown in chat messages

### PR DESCRIPTION
**Pull request by axpoems**
Based on #2250 

* Update dropdown menu on chat messages. Will do the same with the rest of the dropdown menus used in the app as to unify styles.

image

I have created #2251 to improve further the react buttons. Will follow-up with this.

### CODE REVIEW

**Comment by kciouv** [comment]
Nit / Concept ACK

Before:
image

After:
image

The alignment to the right edge feels bad. You can move your mouse directly up from the "more options" button, and if you're too far to the right, none of the dropdown options will be within your reach because of the padding/margin. The new dropdowns are aesthetically a large improvement, but this also removes the present way to copy and paste messages.

**Comment by axpoems** [comment]
Thanks for the feedback/suggestions. This PR is part of a broader effort so more changes will come.
The removal of the copy functionality was intended in the dropdown menu. It was meant to be added outside - I have added it now. Thanks for the remainder.

**Review by djing-chan — APPROVED** [review]
utACK

**Comment by djing-chan** [comment]
@axpoems Can you resolved the conflicts?

**Comment by axpoems** [comment]
> @axpoems Can you resolved the conflicts?

Fixed now.

**Pull request merged**
