### PR TITLE
Fix ES translation

### PR DESCRIPTION
**Pull request by namloan**
Added missing ending "?"

### CODE REVIEW

**Comment by HenrikJannsen** [comment]
@namloan We use Transifex for translations. Any change in the non-english property files would get overwritten when synced with Transifex. I am not familiar with the exact process. @hiciefte is leading Transifex.

**Review by HenrikJannsen — CHANGES_REQUESTED** [review]
NACK

**Comment by namloan** [comment]
Ah true... let me figure out how to do it

**Comment by namloan** [comment]
We have this guide in [translations.md](https://github.com/bisq-network/bisq2/blob/10a39701c5a002401fcc28f439f7f25d6ebbcb51/docs/translations.md#user-content-fn-2-317e8153834ad70f554fb62024fd0c6d):

> Get an API token[2](https://github.com/bisq-network/bisq2/blob/10a39701c5a002401fcc28f439f7f25d6ebbcb51/docs/translations.md#user-content-fn-2-317e8153834ad70f554fb62024fd0c6d) from your Transifex user profile. You have to have project maintainer rights to be able to manipulate the translation files on transifex. Contact to Transifex maintainer to the get the required permissions.

@hiciefte any chance I can get these permissions? @HenrikJannsen maybe you have them?

**Comment by MwithM** [comment]
You need to ask for the permission at transifex, I will need to accept it.

**Comment by namloan** [comment]
Thanks a lot @MwithM! Closing this PR then.

**Pull request closed without merging**
