### PR TITLE
Translated Bisq Easy resources into Italian

### PR DESCRIPTION
**Pull request by super-e**
Bisq Easy resources were wrongly translated in Portuguese. Completed the translation into Italian.
#1858

### CODE REVIEW

**Comment by hiciefte** [comment]
There are updated source files that are not reflected in all languages in the main repository yet.

Could you please review these chatGPT translated versions as well?

1.
```
bisqEasy.price.warn.invalidPrice.notSet=You have not set a price.
bisqEasy.price.warn.invalidPrice.outOfRange=The price you entered is outside the permitted range of -10% to 50%.
bisqEasy.price.warn.invalidPrice.numberFormatException=The price you entered is not a valid number.
bisqEasy.price.warn.invalidPrice.exception=The price you entered is invalid.\n\nError message: {0}
```
chatGPT
```
bisqEasy.price.warn.invalidPrice.notSet=Non hai impostato un prezzo.
bisqEasy.price.warn.invalidPrice.outOfRange=Il prezzo inserito è fuori dall'intervallo consentito del -10% al 50%.
bisqEasy.price.warn.invalidPrice.numberFormatException=Il prezzo inserito non è un numero valido.
bisqEasy.price.warn.invalidPrice.exception=Il prezzo inserito non è valido.\n\nMessaggio di errore: {0}
```
2.
```
bisqEasy.takeOffer.review.sendTakeOfferMessageFeedback.headline=Sending take-offer message
bisqEasy.takeOffer.review.sendTakeOfferMessageFeedback.subTitle=Sending the take-offer message can take up to 2 minutes
bisqEasy.takeOffer.review.sendTakeOfferMessageFeedback.info=Do not close the window or the application until you see the confirmation that the take-offer request was successfully sent.
```
chatGPT
```
bisqEasy.takeOffer.review.sendTakeOfferMessageFeedback.headline=Invio del messaggio di accettazione offerta
bisqEasy.takeOffer.review.sendTakeOfferMessageFeedback.subTitle=L'invio del messaggio di accettazione offerta può richiedere fino a 2 minuti
bisqEasy.takeOffer.review.sendTakeOfferMessageFeedback.info=Non chiudere la finestra o l'applicazione fino a quando non vedi la conferma che la richiesta di accettazione dell'offerta è stata inviata con successo.
```
3.
```
bisqEasy.offerbook.marketListCell.favourites.tooltip.addToFavourites=Add to favourites
bisqEasy.offerbook.marketListCell.favourites.tooltip.removeFromFavourites=Remove from favourites

bisqEasy.offerbook.dropdownMenu.sortAndFilterMarkets.tooltip=Sort and filter markets
bisqEasy.offerbook.dropdownMenu.sortAndFilterMarkets.sortTitle=Sort by:
bisqEasy.offerbook.dropdownMenu.sortAndFilterMarkets.mostOffers=Most offers
bisqEasy.offerbook.dropdownMenu.sortAndFilterMarkets.nameAZ=Name A-Z
bisqEasy.offerbook.dropdownMenu.sortAndFilterMarkets.nameZA=Name Z-A
bisqEasy.offerbook.dropdownMenu.sortAndFilterMarkets.filterTitle=Show markets:
bisqEasy.offerbook.dropdownMenu.sortAndFilterMarkets.withOffers=With offers
bisqEasy.offerbook.dropdownMenu.sortAndFilterMarkets.favourites=Only favourites
bisqEasy.offerbook.dropdownMenu.sortAndFilterMarkets.all=All

bisqEasy.offerbook.dropdownMenu.filterOffersByDirectionOrOwner.tooltip=Filter by offer type
bisqEasy.offerbook.dropdownMenu.filterOffersByDirectionOrOwner.allOffers=All offers
bisqEasy.offerbook.dropdownMenu.filterOffersByDirectionOrOwner.myOffers=My offers
bisqEasy.offerbook.dropdownMenu.filterOffersByDirectionOrOwner.buyOffers=Sell Bitcoin
bisqEasy.offerbook.dropdownMenu.filterOffersByDirectionOrOwner.sellOffers=Buy Bitcoin

bisqEasy.offerbook.dropdownMenu.filterOffersByPeerReputation.tooltip=Filter by peer reputation
bisqEasy.offerbook.dropdownMenu.filterOffersByPeerReputation.atLeastTitle=At least:
bisqEasy.offerbook.dropdownMenu.filterOffersByPeerReputation.allReputations=All reputations
bisqEasy.offerbook.dropdownMenu.filterOffersByPeerReputation.fiveStars=5 stars
bisqEasy.offerbook.dropdownMenu.filterOffersByPeerReputation.atLeastFourStars=4 stars
bisqEasy.offerbook.dropdownMenu.filterOffersByPeerReputation.atLeastThreeStars=3 stars
bisqEasy.offerbook.dropdownMenu.filterOffersByPeerReputation.atLeastTwoStars=2 stars
bisqEasy.offerbook.dropdownMenu.filterOffersByPeerReputation.atLeastOneStar=1 star

bisqEasy.offerbook.chatMessage.deleteOffer.confirmation=Are you sure you want to delete this offer?
```

chatGPT
```
bisqEasy.offerbook.marketListCell.favourites.tooltip.addToFavourites=Aggiungi ai preferiti
bisqEasy.offerbook.marketListCell.favourites.tooltip.removeFromFavourites=Rimuovi dai preferiti

bisqEasy.offerbook.dropdownMenu.sortAndFilterMarkets.tooltip=Ordina e filtra i mercati
bisqEasy.offerbook.dropdownMenu.sortAndFilterMarkets.sortTitle=Ordina per:
bisqEasy.offerbook.dropdownMenu.sortAndFilterMarkets.mostOffers=Più offerte
bisqEasy.offerbook.dropdownMenu.sortAndFilterMarkets.nameAZ=Nome A-Z
bisqEasy.offerbook.dropdownMenu.sortAndFilterMarkets.nameZA=Nome Z-A
bisqEasy.offerbook.dropdownMenu.sortAndFilterMarkets.filterTitle=Mostra mercati:
bisqEasy.offerbook.dropdownMenu.sortAndFilterMarkets.withOffers=Con offerte
bisqEasy.offerbook.dropdownMenu.sortAndFilterMarkets.favourites=Solo preferiti
bisqEasy.offerbook.dropdownMenu.sortAndFilterMarkets.all=Tutti

bisqEasy.offerbook.dropdownMenu.filterOffersByDirectionOrOwner.tooltip=Filtrare per tipo di offerta
bisqEasy.offerbook.dropdownMenu.filterOffersByDirectionOrOwner.allOffers=Tutte le offerte
bisqEasy.offerbook.dropdownMenu.filterOffersByDirectionOrOwner.myOffers=Le mie offerte
bisqEasy.offerbook.dropdownMenu.filterOffersByDirectionOrOwner.buyOffers=Vendi Bitcoin
bisqEasy.offerbook.dropdownMenu.filterOffersByDirectionOrOwner.sellOffers=Compra Bitcoin

bisqEasy.offerbook.dropdownMenu.filterOffersByPeerReputation.tooltip=Filtrare per reputazione del peer
bisqEasy.offerbook.dropdownMenu.filterOffersByPeerReputation.atLeastTitle=Almeno:
bisqEasy.offerbook.dropdownMenu.filterOffersByPeerReputation.allReputations=Tutte le reputazioni
bisqEasy.offerbook.dropdownMenu.filterOffersByPeerReputation.fiveStars=5 stelle
bisqEasy.offerbook.dropdownMenu.filterOffersByPeerReputation.atLeastFourStars=4 stelle
bisqEasy.offerbook.dropdownMenu.filterOffersByPeerReputation.atLeastThreeStars=3 stelle
bisqEasy.offerbook.dropdownMenu.filterOffersByPeerReputation.atLeastTwoStars=2 stelle
bisqEasy.offerbook.dropdownMenu.filterOffersByPeerReputation.atLeastOneStar=1 stella

bisqEasy.offerbook.chatMessage.deleteOffer.confirmation=Sei sicuro di voler eliminare questa offerta?
```
4.
```
bisqEasy.openTrades.rejectTrade.warning=Since the exchange of account details has not yet started, rejecting the trade does not constitute a violation of the trade rules.\n\nIf you have any questions or encounter issues, please don't hesitate to contact your trade peer or seek assistance in the 'Support section'.\n\nAre you sure you want to reject the trade?
```

chatGPT
```
bisqEasy.openTrades.rejectTrade.warning=Dato che lo scambio dei dettagli del conto non è ancora iniziato, rifiutare la negoziazione non costituisce una violazione delle regole di scambio.\n\nSe hai domande o incontri problemi, non esitare a contattare il tuo partner di scambio o a cercare assistenza nella sezione 'Supporto'.\n\nSei sicuro di voler rifiutare la negoziazione?
```
5.
```
bisqEasy.mediation.requester.systemMessage={0} requested mediation
```

chatGPT
```
{0} ha richiesto la mediazione
```

**Comment by hiciefte** [comment]
@super-e Would you be up to translate a couple of new keys as well? If so maybe @mwithm could invite you to Transifex and  I would post all keys were the source was changed or which new keys have been added. WDYT?

**Comment by HenrikJannsen** [comment]
@hiciefte  @super-e Any update here? We want to release soon...

**Comment by HenrikJannsen** [comment]
@hiciefte Can this PR be closed?

**Comment by hiciefte** [comment]
> @hiciefte Can this PR be closed?

As mentioned in the chat - yes. I copied over the work from @super-e, pushed it to Transifex, pulled and committed it (https://github.com/bisq-network/bisq2/pull/2010/commits/727a56ad976dc58750a870cf20c10932955d5686) afterwards with all other languages in #2010

**Comment by super-e** [comment]
Thanks, sorry for the late reply, somehow all GitHub notification emails ended up in spam.
I'm happy to help in Transifex for the future if necessary.
-E-

**Pull request closed without merging**
