### PR TITLE
Toggle button auto-slide component

### LINKED ISSUE #270: Make autoSlide Togglebox component
As we got rid of the JFoenix dependency we need a replacement for the autoSlide Togglebox component.
At first its ok to only have it graphically equvalent, no animations needed. Minimal animations can be added in a second step.
Does not need to be a full JavaFx compliant component but can be a simple higher level composition component.

@xyzmaker123 Interested in that task?

### PR DESCRIPTION
**Pull request by xyzmaker123**
Fixes #270

toggle-button

### CODE REVIEW

**Comment by chimp1984** [comment]
@xyzmaker123 You need to set up commit signing

**Review by chimp1984 — APPROVED** [review]
utACK

**Comment by xyzmaker123** [comment]
@chimp1984 OK - I just pushed signed commit

**Comment by chimp1984** [comment]
The failed build is likely from a failed test in that branch (fixed in more recent main branch).

**Pull request merged**
