### PR TITLE
Upgrade to java22

### PR DESCRIPTION
**Pull request by HenrikJannsen**
Follow up from https://github.com/bisq-network/bisq2/pull/2225

### CODE REVIEW

**Comment by kciouv** [comment]
I couldn't get it building on Linux, but I was busy today and didn't have time to read the error messages, so it might not be an issue with the code rather my development environment.

**Comment by namloan** [comment]
Tested on OS X Sonoma 14.4 - it's not necessarily faster with the current amount of messages / offers but looks smooth and stable.

**Comment by djing-chan** [comment]
@alvasw It seems update to Java 21 or 22 is technically not a big burden (not checked all build targets like packaging).
What do you think about it?

**Comment by HenrikJannsen** [comment]
Will be replaced soon by a updated PR

**Pull request closed without merging**
